//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int id { get; set; }
        public Nullable<int> idRealtor { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idRealProperties { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual RealProperties RealProperties { get; set; }
        public virtual Realtor Realtor { get; set; }
    }
}
