//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealProperties
    {
        public int id { get; set; }
        public Nullable<int> NumberOfFloors { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public string Square { get; set; }
        public string Сity { get; set; }
        public Nullable<int> Longitude { get; set; }
        public Nullable<int> Latitude { get; set; }
        public string Street { get; set; }
        public string ApartmentNumber { get; set; }
        public string HouseNumber { get; set; }
        public Nullable<int> Floor { get; set; }
        public string Type { get; set; }
    }
}
